name: Tagging Repo

on:
  push:

jobs:
  tagging:
    name: Tagging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Tag Repo
        uses: MacroFab/MFDevelopment/actions/tag

  step2:
    name: Step 2
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    needs: tagging
    steps:
      - name: Next step
        run: echo Next step